### ISSUE TITLE
cihoshit

### ISSUE THREAD

**Issue by jaackkiscool** [juNstring/cracks#1]
i've talked with the braindead owner before last time he gave me the code it was just minified, did you just beautify the code lol? 💀

**Comment by juNstring** [comment]
> i've talked with the braindead owner before last time he gave me the code it was just minified, did you just beautify the code lol? 💀

Yes, the owner is retarded and he's a child 💀 I were using fiddler when i found this garbage script, so i just got the source from the HTTP.
